-- Oracle Schema for Pill Tracer

-- Branches Table
CREATE TABLE branches (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    address VARCHAR2(4000),
    city VARCHAR2(100),
    country VARCHAR2(100) DEFAULT 'Pakistan',
    firebase_uid VARCHAR2(128),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Users Table
CREATE TABLE users (
    id VARCHAR2(128) PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    pharmacy_name VARCHAR2(255),
    role VARCHAR2(50) DEFAULT 'pharmacy_admin' NOT NULL,
    status VARCHAR2(50) DEFAULT 'pending', 
    branch_id NUMBER,
    phone VARCHAR2(50),
    address VARCHAR2(4000),
    license_number VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,
    CONSTRAINT fk_users_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL
);

-- Medicines Table
CREATE TABLE medicines (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(4000),
    manufacturer VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Inventory Records Table
CREATE TABLE inventory_records (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    medicine_id NUMBER,
    medicine_name VARCHAR2(255),
    description VARCHAR2(4000),
    branch_id NUMBER NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    quantity NUMBER DEFAULT 0 NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR2(128),
    CONSTRAINT fk_inv_medicine FOREIGN KEY (medicine_id) REFERENCES medicines(id) ON DELETE SET NULL,
    CONSTRAINT fk_inv_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT fk_inv_user FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
);

-- Activity Logs Table
CREATE TABLE activity_logs (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(128),
    action VARCHAR2(50) NOT NULL,
    resource_type VARCHAR2(50) NOT NULL,
    details VARCHAR2(4000), -- Store JSON as string
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Indexes
CREATE INDEX idx_medicines_name ON medicines(name);
CREATE INDEX idx_branches_city ON branches(city);
